insert into public.comparisons (software_a_id, software_b_id, custom_verdict, status) values
((select id from public.software where slug = 'sevdesk'), (select id from public.software where slug = 'lexware-office'), null, 'published'),
((select id from public.software where slug = 'lexware-office'), (select id from public.software where slug = 'datev-unternehmen-online'), null, 'published'),
((select id from public.software where slug = 'sevdesk'), (select id from public.software where slug = 'buchhaltungsbutler'), null, 'published'),
((select id from public.software where slug = 'sage-active'), (select id from public.software where slug = 'lexware-office'), null, 'published'),
((select id from public.software where slug = 'personio'), (select id from public.software where slug = 'hrworks'), null, 'published'),
((select id from public.software where slug = 'personio'), (select id from public.software where slug = 'factorial'), null, 'published'),
((select id from public.software where slug = 'hubspot'), (select id from public.software where slug = 'pipedrive'), null, 'published'),
((select id from public.software where slug = 'salesforce'), (select id from public.software where slug = 'hubspot'), null, 'published'),
((select id from public.software where slug = 'weclapp'), (select id from public.software where slug = 'xentral'), null, 'published'),
((select id from public.software where slug = 'awork'), (select id from public.software where slug = 'stackfield'), null, 'published'),
((select id from public.software where slug = 'clockodo'), (select id from public.software where slug = 'papershift'), null, 'published'),
((select id from public.software where slug = 'docuware'), (select id from public.software where slug = 'ecodms'), null, 'published'),
((select id from public.software where slug = 'sage-50-connected'), (select id from public.software where slug = 'lexware-office'), null, 'published'),
((select id from public.software where slug = 'sage-active'), (select id from public.software where slug = 'sevdesk'), null, 'published'),
((select id from public.software where slug = 'sage-50-connected'), (select id from public.software where slug = 'datev-unternehmen-online'), null, 'published'),
((select id from public.software where slug = 'sage-hr-payroll'), (select id from public.software where slug = 'personio'), null, 'published'),
((select id from public.software where slug = 'sage-hr-payroll'), (select id from public.software where slug = 'lexware-lohn-gehalt'), null, 'published'),
((select id from public.software where slug = 'sage-100'), (select id from public.software where slug = 'dynamics-365-business-central'), null, 'published'),
((select id from public.software where slug = 'sage-50-handwerk'), (select id from public.software where slug = 'orgamax'), null, 'published'),
((select id from public.software where slug = 'wiso-meinbuero'), (select id from public.software where slug = 'lexware-office'), null, 'published'),
((select id from public.software where slug = 'jtl-wawi'), (select id from public.software where slug = 'xentral'), null, 'published')
on conflict (software_a_id, software_b_id) do update set custom_verdict = excluded.custom_verdict;

insert into public.software_alternatives (software_id, alternative_id, display_order) values
((select id from public.software where slug = 'sevdesk'), (select id from public.software where slug = 'lexware-office'), 0),
((select id from public.software where slug = 'sevdesk'), (select id from public.software where slug = 'sage-active'), 1),
((select id from public.software where slug = 'sevdesk'), (select id from public.software where slug = 'buchhaltungsbutler'), 2),
((select id from public.software where slug = 'sevdesk'), (select id from public.software where slug = 'papierkram'), 3),
((select id from public.software where slug = 'lexware-office'), (select id from public.software where slug = 'sevdesk'), 0),
((select id from public.software where slug = 'lexware-office'), (select id from public.software where slug = 'sage-active'), 1),
((select id from public.software where slug = 'lexware-office'), (select id from public.software where slug = 'wiso-meinbuero'), 2),
((select id from public.software where slug = 'lexware-office'), (select id from public.software where slug = 'papierkram'), 3),
((select id from public.software where slug = 'sage-active'), (select id from public.software where slug = 'lexware-office'), 0),
((select id from public.software where slug = 'sage-active'), (select id from public.software where slug = 'sevdesk'), 1),
((select id from public.software where slug = 'sage-active'), (select id from public.software where slug = 'sage-50-connected'), 2),
((select id from public.software where slug = 'sage-active'), (select id from public.software where slug = 'buchhaltungsbutler'), 3),
((select id from public.software where slug = 'sage-50-connected'), (select id from public.software where slug = 'sage-active'), 0),
((select id from public.software where slug = 'sage-50-connected'), (select id from public.software where slug = 'lexware-office'), 1),
((select id from public.software where slug = 'sage-50-connected'), (select id from public.software where slug = 'orgamax'), 2),
((select id from public.software where slug = 'sage-50-connected'), (select id from public.software where slug = 'wiso-meinbuero'), 3),
((select id from public.software where slug = 'personio'), (select id from public.software where slug = 'hrworks'), 0),
((select id from public.software where slug = 'personio'), (select id from public.software where slug = 'sage-hr-payroll'), 1),
((select id from public.software where slug = 'personio'), (select id from public.software where slug = 'factorial'), 2),
((select id from public.software where slug = 'personio'), (select id from public.software where slug = 'kenjo'), 3),
((select id from public.software where slug = 'sage-hr-payroll'), (select id from public.software where slug = 'personio'), 0),
((select id from public.software where slug = 'sage-hr-payroll'), (select id from public.software where slug = 'lexware-lohn-gehalt'), 1),
((select id from public.software where slug = 'sage-hr-payroll'), (select id from public.software where slug = 'factorial'), 2),
((select id from public.software where slug = 'sage-hr-payroll'), (select id from public.software where slug = 'datev-lohn-und-gehalt'), 3),
((select id from public.software where slug = 'sage-100'), (select id from public.software where slug = 'dynamics-365-business-central'), 0),
((select id from public.software where slug = 'sage-100'), (select id from public.software where slug = 'weclapp'), 1),
((select id from public.software where slug = 'sage-100'), (select id from public.software where slug = 'sap-business-one'), 2),
((select id from public.software where slug = 'sage-100'), (select id from public.software where slug = 'myfactory'), 3),
((select id from public.software where slug = 'orgamax'), (select id from public.software where slug = 'sage-50-handwerk'), 0),
((select id from public.software where slug = 'orgamax'), (select id from public.software where slug = 'sage-50-connected'), 1),
((select id from public.software where slug = 'orgamax'), (select id from public.software where slug = 'wiso-meinbuero'), 2),
((select id from public.software where slug = 'orgamax'), (select id from public.software where slug = 'lexware-office'), 3)
on conflict (software_id, alternative_id) do update set display_order = excluded.display_order;
