// Downloads the official brand icon for every product without a bundled logo.
// Source: the vendor's own website only (apple-touch-icon, then the largest <link rel="icon">).
// Writes public/logos/<slug>.<ext> and lib/data/logos-fetched.ts. Re-runnable; existing files are kept.
import { createJiti } from "jiti";
import { existsSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const jiti = createJiti(import.meta.url, { alias: { "@": root }, interopDefault: true });
const { SOFTWARE } = await jiti.import(path.join(root, "lib/data/index.ts"));
const { PRODUCT_LOGOS } = await jiti.import(path.join(root, "lib/data/logos.ts"));

const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126 Safari/537.36";
const TYPES = { "image/png": "png", "image/svg+xml": "svg", "image/webp": "webp", "image/jpeg": "jpg", "image/x-icon": "ico", "image/vnd.microsoft.icon": "ico" };
const MAX = 500 * 1024;

async function get(url) {
  const res = await fetch(url, { headers: { "user-agent": UA, accept: "text/html,image/*;q=0.9,*/*;q=0.8" }, redirect: "follow", signal: AbortSignal.timeout(15000) });
  return res;
}

function candidates(html, base) {
  const out = [];
  for (const m of html.matchAll(/<link\b[^>]*>/gi)) {
    const tag = m[0];
    const rel = (tag.match(/rel=["']([^"']+)["']/i) || [])[1]?.toLowerCase() ?? "";
    const href = (tag.match(/href=["']([^"']+)["']/i) || [])[1];
    if (!href || !/icon/.test(rel)) continue;
    const size = Number(((tag.match(/sizes=["'](\d+)x\d+["']/i) || [])[1]) ?? 0);
    const isSvg = /\.svg(\?|$)/i.test(href) || /svg/i.test(tag);
    const score = (rel.includes("apple-touch-icon") ? 1000 : 0) + (isSvg ? 900 : 0) + size;
    try {
      out.push({ url: new URL(href.replace(/&amp;/g, "&"), base).href, score });
    } catch {}
  }
  out.push({ url: new URL("/apple-touch-icon.png", base).href, score: 1 });
  return out.sort((a, b) => b.score - a.score);
}

const fetched = {};
const missing = [];
for (const s of SOFTWARE) {
  if (PRODUCT_LOGOS[s.slug] || !s.vendor_website) continue;
  const already = ["png", "svg", "webp", "jpg", "ico"].find((e) => existsSync(path.join(root, "public/logos", `${s.slug}.${e}`)));
  if (already) {
    fetched[s.slug] = `/logos/${s.slug}.${already}`;
    continue;
  }
  let ok = false;
  try {
    const page = await get(s.vendor_website);
    const html = await page.text();
    for (const c of candidates(html, page.url)) {
      try {
        const r = await get(c.url);
        const type = (r.headers.get("content-type") || "").split(";")[0].trim();
        const ext = TYPES[type];
        if (!r.ok || !ext) continue;
        const buf = Buffer.from(await r.arrayBuffer());
        if (buf.length < 200 || buf.length > MAX) continue;
        if (ext === "svg" && /<script/i.test(buf.toString("utf8"))) continue; // never ship scriptable SVGs
        writeFileSync(path.join(root, "public/logos", `${s.slug}.${ext}`), buf);
        fetched[s.slug] = `/logos/${s.slug}.${ext}`;
        console.log(`ok   ${s.slug.padEnd(32)} ${c.url} (${Math.round(buf.length / 1024)} KB)`);
        ok = true;
        break;
      } catch {}
    }
  } catch (e) {
    console.log(`fail ${s.slug.padEnd(32)} ${e.message}`);
  }
  if (!ok) missing.push(s.slug);
}

writeFileSync(
  path.join(root, "lib/data/logos-fetched.ts"),
  `/** Generated by scripts/fetch-logos.mjs from the vendors' own websites. Do not edit by hand. */\nexport const FETCHED_LOGOS: Record<string, string> = ${JSON.stringify(fetched, null, 2)};\n`,
);
console.log(`\n${Object.keys(fetched).length} Logos, ohne Logo: ${missing.join(", ") || "keine"}`);
